version: '3.8'

services:
  pdfbuddy:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=${SECRET_KEY:-change-this-in-production}
      - FLASK_ENV=production
      - OLLAMA_URL=http://ollama:11434/api/generate
      - DATABASE_PATH=/app/data/chatbot.db
    volumes:
      - pdfbuddy_data:/app/data
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - pdfbuddy-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    networks:
      - pdfbuddy-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  ollama_data:
  pdfbuddy_data:

networks:
  pdfbuddy-network:
    driver: bridge
